### ISSUE TITLE
Adguard integration with Hassio

### ISSUE THREAD

**Issue by abeverwijk** [hassio-addons/addon-adguard-home#21]
# Problem/Motivation

Hassio 0.94.2
Intel NUC
After installing adguard addon(1.2.0) the integration field in Hassio is blank. You cannot add it to Hassio.

## Expected behavior

Succesfull integration configuration and the availability of adguard sensors and switches in HA.

## Actual behavior

Configuration of integration not possible and the following error:

2019-06-12 19:00:21 ERROR (MainThread) [homeassistant.config_entries] Cannot find integration adguard
2019-06-12 19:00:21 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 671, in _async_create_flow
    self.hass, handler_key)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 211, in async_get_integration
    raise IntegrationNotFound(domain)
homeassistant.loader.IntegrationNotFound: Component adguard not found.
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/discovery.py", line 89, in async_process_new
    service, context={'source': 'hassio'}, data=config_data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 64, in async_init
    handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 674, in _async_create_flow
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler
2019-06-12 19:14:09 ERROR (MainThread) [homeassistant.config_entries] Cannot find integration adguard

## Steps to reproduce

remove and re-install the addon

## Proposed changes

I hope you can find out whats wrong

**Comment by frenck** [comment]
That is expected since the integration for Home Assistant isn't released yet.

**Comment by abeverwijk** [comment]
Sorry, didn't know that. I saw some integration pictures on you twitter account and together with the error I thought something was wrong. I'll be more patient then :)

**Comment by tukadafoonday** [comment]
Oh, glad that's the case as it's been driving me mad....

I will also be more patient.

**Comment by gekomax** [comment]
Same problem here...
