### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by itssimon** [hassio-addons/addon-adguard-home#22]
The add-on version 1.2.0 doesn't start anymore. See logs below.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 1.2.0
 You are running the latest version of this add-on.
 System: Resin OS 2.3.0+rev1  (armv7 / raspberrypi3)
 Home Assistant version: 0.94.2
 Supervisor version: 166
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adguard.sh: executing... 
[cont-init.d] adguard.sh: exited 0.
[cont-init.d] discovery.sh: executing... 
{"uuid":"7483d39824224e9aab1ce9266a24762c"}
[23:23:21] INFO: Successfully send discovery information to Home Assistant.
[cont-init.d] discovery.sh: exited 0.
[cont-init.d] hosts.sh: executing... 
[cont-init.d] hosts.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:23:21] INFO: Starting AdGuard Home server...
2019/06/16 23:23:22 [info] AdGuard Home, version v0.96-hotfix, channel release
2019/06/16 23:23:22 [info] Added 8 client aliases from /etc/hosts
2019/06/16 23:23:22 [info] Upstream 0: 192.168.1.99:55
2019/06/16 23:23:25 [info] Start DNS server periodic jobs
2019/06/16 23:23:25 [info] Starting the DNS proxy server
2019/06/16 23:23:25 [info] Ratelimit is enabled and set to 20 rps
2019/06/16 23:23:25 [info] The server is configured to refuse ANY requests
2019/06/16 23:23:25 [info] DNS cache is enabled
2019/06/16 23:23:25 [info] Creating the UDP server socket
2019/06/16 23:23:25 [info] Listening to udp://[::]:53
2019/06/16 23:23:25 [info] Creating the TCP server socket
2019/06/16 23:23:25 [info] Listening to tcp://[::]:53
2019/06/16 23:23:25 [info] Entering the UDP listener loop on [::]:53
2019/06/16 23:23:25 [info] Entering the tcp listener loop on [::]:53
2019/06/16 23:23:25 [info] Go to http://127.0.0.1:45158
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2c pc=0x1d89a8]
goroutine 50 [running]:
crypto/tls.(*Conn).write(0x3e90000, 0x3eb6000, 0x125, 0x140, 0x3eb4000, 0x120, 0x180)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/crypto/tls/conn.go:896 +0xf4
crypto/tls.(*Conn).writeRecordLocked(0x3e90000, 0x6c9416, 0x3eb4000, 0x120, 0x180, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/crypto/tls/conn.go:945 +0x1fc
crypto/tls.(*Conn).writeRecord(0x3e90000, 0x3eb4016, 0x3eb4000, 0x120, 0x180, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/crypto/tls/conn.go:967 +0x90
crypto/tls.(*Conn).clientHandshake(0x3e90000, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/crypto/tls/handshake_client.go:167 +0x114
crypto/tls.(*Conn).Handshake(0x3e90000, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/crypto/tls/conn.go:1343 +0xe8
net/http.(*persistConn).addTLS.func2(0x0, 0x3e90000, 0x0, 0x20fc140)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/transport.go:1190 +0x34
created by net/http.(*persistConn).addTLS
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/transport.go:1186 +0x174
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by frenck** [comment]
Upstream issue: AdguardTeam/AdGuardHome#831

Resolution/workaround on our end:

Given the nature of DNS and the importance of it running, I should implement auto restart on crash.

**Comment by itssimon** [comment]
The upstream issue seems to be fixed in the edge tag Docker image. Maybe worth updating to that one?

**Comment by frenck** [comment]
I'm not shipping edge/beta software in add-ons, sorry.

**Comment by itssimon** [comment]
That makes sense, however if the stable one doesn't even start don't you think as an interim solution the edge one would be better?

**Comment by frenck** [comment]
@itssimon You should ask the AdGuard Team that question IMHO.

**Comment by itssimon** [comment]
Yeah, fair enough. But they've fixed the problem and their direct users can choose to run the edge version if they're encountering this bug. Hass.io add-on users don't get to choose and rely on you to release a fixed version.

**Comment by frenck** [comment]
Hass.io itself does not provide version capabilities, that is a request for Hass.io itself and unfortunately outside of my control.

**Comment by frenck** [comment]
Addressed in the current dev branch, will be part of the next release of the add-on.
